[package]
name = "demise_core"
version = "0.1.0"
authors = ["Christopher Fu <chrisf1337@gmail.com>"]

[dependencies]
buffer = { path = "buffer" }
serde_json = "0.9"
serde = "0.9"
serde_derive = "0.9"
log = "*"
env_logger = "*"
